parameters:
#    acme_guestbook.example.class: Acme\GuestbookBundle\Example

services:
#    acme_guestbook.example:
#        class: %acme_guestbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
